export const CHANGE_RANKING_DETAIL = "CHANGE_RANKING_DETAIL"

export const CHANGE_RANKING_SUBSCRIBERS = "CHANGE_RANKING_SUBSCRIBERS"

export const CHANGE_RANKING_RELATED = "CHANGE_RANKING_RELATED"

export const CHANGE_RANKING_COMMENT = "CHANGE_RANKING_COMMENT"

