export const CHANGE_TOP_BANNERS = "CHANGE_TOP_BANNERS"

export const CHANGE_RECOMMEND_SHEET = "CHANGE_RECOMMEND_SHEET"

export const CHANGE_RECOMMEND_SING = "CHANGE_RECOMMEND_SING"

export const CHANGE_RECOMMEND_SINGER = "CHANGE_RECOMMEND_SINGER"
